insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('1','UNITY','AMK','ANG MO KIO','53 Ang Mo Kio Ave 3','#B2-21/25',null,null,null,null,'569933',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('2','UNITY','ARC','Alexandra Retail Center','460 Alexandra Road','#02-04/05/06',null,null,'Singapore',null,'119963',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('3','UNITY','BDK','BEDOK','Blk 212 Bedok North Street 1','#02-147',null,null,null,null,'460212',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('4','UNITY','BMC','BUKIT MERAH CENTRAL','Blk 166 #01-3531','Bukit Merah Central',null,null,null,null,'150166',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('5','UNITY','BPP','BUKIT PANJANG PLAZA','#01-06 Bukit Panjang Plaza','1 Jelebu Road',null,null,null,null,'677743',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('6','UNITY','BSH','BISHAN','Blk 510 Bishan St 13','#01-520',null,null,null,null,'570510',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('7','UNITY','BTP','BUKIT TIMAH PLAZA','1 Jalan Anak Bukit','#B1-01 Bukit Timah Plaza',null,null,null,null,'588996',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('8','UNITY','CLE','CLEMENTI','Blk 451 #01-307','Clementi Ave 3',null,null,null,null,'120451',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('9','UNITY','CMA','Clementi Mall','3155 Commonwealth Ave West','#B1-10/11 The Clementi Mall',null,null,null,null,'129588',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('10','UNITY','DSN','DAWSON ROAD','Blk 57 Dawson Road','#01-10A Dawson Place',null,null,null,null,'142057',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('11','UNITY','ESP','EASTPOINT MALL','3 Simei Street 6','#B1-05/07',null,null,null,null,'528833',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('12','UNITY','FCT','FORTUNE CENTRE','190 Middle Road','#01-26 Fortune Centre',null,null,null,null,'188979',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('13','UNITY','FTP','FRANCHISE','Blk 829 Tampines St 81','#01-280',null,null,null,null,'520829',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('14','UNITY','GWC','GREAT WORLD CITY','1 Kim Seng Promenade','#B1-14/15 Great World City',null,null,null,null,'237994',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('15','UNITY','HBF','HARBOUR FRONT CENTRE','1 Maritime Square','#02-118/119',null,null,null,null,'99253',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('16','UNITY','HLC','HOUGANG MALL','90 Hougang Ave 10','#B1-35/36',null,null,null,null,'538766',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('17','UNITY','HOU','HOUGANG ST 21','Blk 202 #01-00','Hougang St 21',null,null,null,null,'530202',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('18','UNITY','HPT','HOUGANG POINT','1 Hougang St 91','#02-03 Festive Mkt',null,null,null,null,'538692',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('19','UNITY','HVM','Holland Village MRT','200 Holland Avenue','#B1-05/06/07',null,null,'Singapore',null,'538692',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('20','UNITY','JCU','JCUBE','2 Jurong East Central 1','#B1-05',null,null,'Singapore',null,'538692',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('21','UNITY','JRP','JURONG POINT','1 Jurong West Central 2','#B1-09 Jurong Point',null,null,null,null,'648886',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('22','UNITY','LBR','Change Alley Link Bridge','62 Collyer Quay','#02-01 to 04',null,null,'Singapore',null,'49325',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('23','UNITY','LT1','LOT 1 SHOPPERS MALL','21 Choa Chu Kang Ave 4','#B1-04/05',null,null,null,null,'689812',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('24','UNITY','MPR','MARINE PARADE','No. 6 Marine Parade Central',null,null,null,null,null,'449411',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('25','UNITY','NMA','Nex Mall','23 Serangoon Central','#03-37/38, nex',null,null,null,null,'556083',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('26','UNITY','OAM','100AM','100 Tras Street','#04-06/07',null,null,null,null,'79027',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('27','UNITY','PGP','PUNGGOL PLAZA','Blk 168 Punggol Field','#03-01/02 Punggol Plaza',null,null,null,null,'820168',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('28','UNITY','PSG','Plaza Singapura','68 Orchard Road','Plaza Singapura #B2-20A',null,null,null,null,'238839',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('29','UNITY','RFC','RAFFLES CITY','252 North Bridge Road #B1-44L','Raffles City Shopping Centre',null,null,null,null,'179103',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('30','UNITY','RMA','RIVERVALE MALL','11 Rivervale Crescent','#02-02 Rivervale Mall',null,null,null,null,'545082',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('31','UNITY','RVP','RIVERVALE PLAZA','Blk 118 Rivervale Drive','#01-16 Rivervale Plaza',null,null,null,null,'540118',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('32','UNITY','SPC','SINGAPORE POST CENTRE','10 Eunos Road 8','#B2-10 Singapore Post Centre',null,null,null,null,'408600',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('33','UNITY','SRC','SERANGOON CENTRAL','Blk 266, #01-253','SerangoonCentral Drive',null,null,null,null,'550266',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('34','UNITY','STC','SUNTEC CITY','3 Temasek Boulevard','Suntec City Mall #02-105',null,null,null,null,'38983',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('35','UNITY','TBR','TIONG BAHRU PLAZA','302 Tiong Bahru Road','#B1-11 Tiong Bahru Plaza',null,null,null,null,'168732',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('36','UNITY','TMA','TANGLIN MALL','163 Tanglin Road','#B1-13 Tanglin Mall',null,null,null,null,'247933',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('37','UNITY','TMJ','Taman Jurong Shopping Centre','Blk 399 Yung Sheng Road','#01-35 (part of)',null,null,null,null,'610399',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('38','UNITY','TMT','Tampines Mart','No. 11 Tampines Street 32','#01-11 Tampines Mart',null,null,null,null,'529287',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('39','UNITY','TP3','TOA PAYOH BLK 192','Blk 192 Toa Payoh Lor 4','#02-674',null,null,null,null,'310192',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('40','UNITY','TPC','TAMPINES COMMUNITY CLUB','Blk 866A Tampines St.83','#01-01',null,null,null,null,'521866',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('41','UNITY','TPG','TANJONG PAGAR','Blk5 #01-01Tanjong Pagar Plaza','Tanjong Pagar Plaza',null,null,null,null,'81005',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('42','UNITY','TPM','TAMPINES MALL','4 Tampines Central 5','#B1-12 Tampines Mall',null,null,null,null,'529510',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('43','UNITY','TPO','TAMPINES ONE','10 Tampines Central 1','#B1-11/12 Tampines One',null,null,null,null,'529536',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('44','UNITY','TPY','TOA PAYOH CENTRAL','500 Toa Payoh Lor 6','#B1-30 Toa Payoh Central',null,null,'Singapore',null,'310510',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('45','UNITY','TSP','THOMSON PLAZA','301 Upper Thomson Road','#01-102 Thomson Plaza',null,null,null,null,'574408',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('46','UNITY','WCC','WOODLANDS CIVIC CENTRE','900 South Woodlands Drive','#B1-01 Woodlands Civic Centre',null,null,'Singapore',null,'730900',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('47','UNITY','WCP','WEST COAST PLAZA','154 West Coast Road','#B1-14 West Coast Plaza',null,null,null,null,'127371',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('48','UNITY','WMA','WEST MALL','1 Bukit Batok Central Link','#01-08 West Mall',null,null,'Singapore',null,'658713',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('49','UNITY','WSA','WHITE SANDS','1, Pasir Ris Central St.3','#01-12/12A',null,null,null,null,'518457',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('50','UNITY','YS1','Yishun Blk 291','Block 291 Yishun Street 22','#01-351',null,null,null,null,'760291',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('51','UNITY','YSH','YISHUN','Blk 849 Yishun Ring Road','#01-3703',null,null,null,null,'760849',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('52','UNITY','YTP','YEW TEE POINT','21 Choa Chu Kang North 6','#B1-08/09 Yew Tee Point',null,null,null,null,'689578',null,now(),false);
insert into BUYER_STORE(STORE_OID,BUYER_CODE,STORE_CODE,STORE_NAME,STORE_ADDR1,STORE_ADDR2,STORE_ADDR3,STORE_ADDR4,STORE_CITY,STORE_STATE,STORE_POSTAL_CODE,STORE_CTRY_CODE,CREATE_DATE,IS_WAREHOUSE)
values('53','UNITY','KMA','Katong Mall','112 East Coast Road','#B1-08 Katong Mall',null,null,'Singapore',null,'428802',null,now(),false);