insert into CURRENCY(CURR_CODE,CURR_DESC) values('AED','UAE Dirham');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('AFN','Afghani');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ALL','Lek');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('AMD','Armenian Dram');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ANG','Netherlands Antillian Guilder');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('AOA','Kwanza');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ARS','Argentine Peso');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('AUD','Australian Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('AWG','Aruban Guilder');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('AZN','Azerbaijanian Manat');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BAM','Convertible Marks');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BBD','Barbados Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BDT','Taka');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BGN','Bulgarian Lev');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BHD','Bahraini Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BIF','Burundi Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BMD','Bermudian Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BND','Brunei Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BRL','Brazilian Real');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BSD','Bahamian Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BWP','Pula');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BYR','Belarussian Ruble');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('BZD','Belize Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CAD','Canadian Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CDF','Franc Congolais');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CHF','Swiss Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CNY','Yuan Renminbi');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CRC','Costa Rican Colon');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CUP','Cuban Peso');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CVE','Cape Verde Escudo');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('CZK','Czech Koruna');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('DJF','Djibouti Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('DKK','Danish Krone');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('DOP','Dominican Peso');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('DZD','Algerian Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('EEK','Kroon');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('EGP','Egyptian Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ERN','Nakfa');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ETB','Ethiopian Birr');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('EUR','Euro');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('FJD','Fiji Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('FKP','Falkland Islands Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GBP','Pound Sterling');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GEL','Lari');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GHS','Ghana Cedi');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GIP','Gibraltar Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GMD','Dalasi');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GNF','Guinea Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GTQ','Quetzal');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('GYD','Guyana Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('HKD','Hong Kong Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('HNL','Lempira');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('HRK','Croatian Kuna');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('HUF','Forint');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('IDR','Rupiah');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ILS','New Israeli Sheqel');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('INR','Indian Rupee');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('IQD','Iraqi Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('IRR','Iranian Rial');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ISK','Iceland Krona');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('JMD','Jamaican Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('JOD','Jordanian Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('JPY','Yen');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KES','Kenyan Shilling');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KGS','Som');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KHR','Riel');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KMF','Comoro Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KPW','North Korean Won');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KRW','Won');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KWD','Kuwaiti Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KYD','Cayman Islands Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('KZT','Tenge');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LAK','Kip');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LBP','Lebanese Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LKR','Sri Lanka Rupee');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LRD','Liberian Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LTL','Lithuanian Litas');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LVL','Latvian Lats');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('LYD','Libyan Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MAD','Moroccan Dirham');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MDL','Moldovan Leu');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MGA','Malagasy Ariary');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MKD','Denar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MMK','Kyat');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MNT','Tugrik');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MOP','Pataca');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MRO','Ouguiya');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MUR','Mauritius Rupee');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MVR','Rufiyaa');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MWK','Kwacha');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MYR','Malaysian Ringgit');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('MZN','Metical');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('NGN','Naira');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('NIO','Cordoba Oro');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('NOK','Norwegian Krone');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('NPR','Nepalese Rupee');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('NZD','New Zealand Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('OMR','Rial Omani');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('PEN','Nuevo Sol');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('PGK','Kina');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('PHP','Philippine Peso');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('PKR','Pakistan Rupee');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('PLN','Zloty');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('PYG','Guarani');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('QAR','Qatari Rial');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('RON','New Leu');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('RSD','Serbian Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('RUB','Russian Ruble');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('RWF','Rwanda Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SAR','Saudi Riyal');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SBD','Solomon Islands Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SCR','Seychelles Rupee');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SDG','Sudanese Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SEK','Swedish Krona');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SGD','Singapore Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SHP','Saint Helena Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SKK','Slovak Koruna');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SLL','Leone');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SOS','Somali Shilling');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SRD','Surinam Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('STD','Dobra');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SYP','Syrian Pound');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('SZL','Lilangeni');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('THB','Baht');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TJS','Somoni');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TMM','Manat');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TND','Tunisian Dinar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TOP','Pa''anga');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TRY','New Turkish Lira');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TTD','Trinidad and Tobago Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TWD','New Taiwan Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('TZS','Tanzanian Shilling');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('UAH','Hryvnia');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('UGX','Uganda Shilling');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('USD','US Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('UZS','Uzbekistan Sum');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('VEF','Bolivar Fuerte');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('VND','Dong');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('VUV','Vatu');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('WST','Tala');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XAF','CFA Franc BEAC');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XAG','Silver');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XAU','Gold');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XBA','Bond Markets Units European Composite Unit (EURCO)');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XBB','European Monetary Unit (E.M.U.-6)');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XBC','European Unit of Account 9(E.U.A.-9)');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XBD','European Unit of Account 17(E.U.A.-17)');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XCD','East Caribbean Dollar');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XDR','SDR');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XFO','Gold-Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XFU','UIC-Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XOF','CFA Franc BCEAO');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XPD','Palladium');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XPF','CFP Franc');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('XPT','Platinum');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('YER','Yemeni Rial');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ZAR','Rand');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ZMK','Kwacha');
insert into CURRENCY(CURR_CODE,CURR_DESC) values('ZWD','Zimbabwe Dollar');