Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('0001', 'My Task', NULL, NULL, 1, TRUE, 0001, '/taskList/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('1000', 'Administration', NULL, NULL, 1, TRUE, 1000, '/admin/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('2000', 'Role Management', NULL, NULL, 1, TRUE, 2000, '/role/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('3000', 'User Management', NULL, NULL, 1, TRUE, 3000, NULL);

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('3001', 'User Profile', NULL, '3000', 2, TRUE, 3001, '/user/init.action');

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('3002', 'AD User Import', NULL, '3000', 2, TRUE, 3002, '/userImport/init.action');

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('4000', 'Group Management', NULL, NULL, 1, TRUE, 4000, '/group/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('5000', 'Buyer Management', NULL, NULL, 1, TRUE, 5000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('5001', 'Buyer Profile', NULL, '5000', 2, TRUE, 5001, '/buyer/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('5002', 'Buyer Store', NULL, '5000', 2, TRUE, 5002, '/buyerStore/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('6000', 'Supplier Management', NULL, NULL, 1, TRUE, 6000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('6001', 'Supplier Profile', NULL, '6000', 2, TRUE, 6001, '/supplier/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('6002', 'Trading Partner', NULL, '6000', 2, TRUE, 6002, '/tp/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('6003', 'Supplier Group', NULL, '6000', 2, TRUE, 6003, '/supplierSet/init.action');



Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('7000', 'Application Support', NULL, NULL, 1, TRUE, 7000, NULL);

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('7001', 'Log File', NULL, '7000', 2, TRUE, 7001, '/log/init.action');

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('8000', 'Audit Trail', NULL, NULL, 1, TRUE, 8000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('8001', 'Admin', NULL, '8000', 2, TRUE, 8001, '/auditTrail/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('8002', 'System Access', NULL, '8000', 2, TRUE, 8002, '/auditAccess/init.action');

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9000', 'Transactional Docs', NULL, NULL, 1, TRUE, 9000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9001', 'Purchase Order', NULL, '9000', 2, TRUE, 9001, '/po/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9002', 'Return to Vendor', NULL, '9000', 2, TRUE, 9002, '/rtv/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9003', 'Goods Receipt Note', NULL, '9000', 2, TRUE, 9003, '/grn/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9004', 'E-Invoice', NULL, '9000', 2, TRUE, 9004, '/inv/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9005', 'Debit Note', NULL, '9000', 2, TRUE, 9005, '/dn/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9006', 'Delivery Order', NULL, '9000', 2, TRUE, 9006, '/do/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9007', 'Payment Advice', NULL, '9000', 2, TRUE, 9007, '/pn/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9008', 'ItemIn Master', NULL, '9000', 2, TRUE, 9008, '/itemIn/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9009', 'ItemOut Master', NULL, '9000', 2, TRUE, 9009, '/itemOut/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9010', 'Goods Issued', NULL, '9000', 2, TRUE, 9010, '/gi/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9011', 'Credit Claim', NULL, '9000', 2, TRUE, 9011, '/cc/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9012', 'Quick Purchase Order', NULL, '9000', 2, TRUE, 9012, '/quickPo/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9013', 'Daily Sales Data', NULL, '9000', 2, TRUE, 9013, '/sales/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('9014', 'Credit Note', NULL, '9000', 2, TRUE, 9014, '/cn/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('10000', 'Matching Report', NULL, NULL, 1, TRUE, 10000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('10001', 'PO-INV-GRN-DN Matching', NULL, '10000', 2, TRUE, 10001, '/poInvGrnDnMatching/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('10002', 'Matching Run Summary Report', NULL, '10000', 2, TRUE, 10002, '/summaryReport/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('10003', 'Matching Discrepancy Report', NULL, '10000', 2, TRUE, 10003, '/discrepancyReport/init.action');

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('11000', 'Other Reports', NULL, NULL, 1, TRUE, 11000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('11001', 'Read Status Report', NULL, '11000', 2, TRUE, 11001, '/readStatusReport/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('11002', 'Tracking Report', NULL, '11000', 2, TRUE, 11002, '/trackingReport/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('11003', 'Data Export Report', NULL, '11000', 2, TRUE, 11003, '/dataExportReport/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('11004', 'Missing Docs Report', NULL, '11000', 2, TRUE, 11004, '/missingDocsReport/init.action');
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('11006', 'DN Discrepancy Report', NULL, '11000', 2, TRUE, 11006, '/dnDiscrepancyReport/init.action');


Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('20000', 'Jobs', NULL, NULL, 1, TRUE, 20000, NULL);
Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('20001', 'Job Control', NULL, '20000', 2, TRUE, 11001, '/jobControl/init.action');

Insert into MODULE(MODULE_ID, MODULE_NAME, MODULE_TITLE_KEY, PARENT_ID, MODULE_LEVEL, SHOWABLE, SHOW_SORT, MODULE_LINK)
VALUES('21001', 'Generate Batch Invoice', NULL, '21001', 1, TRUE, 21001, '/testDocs/initGenerateBatchInvoice.action');