


-- Task List Module
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('000101', 'Task List - [View]', 0, FALSE, 'VIEW', '0001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('000101', '/taskList/checkPendingUser.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('000101', '/taskList/checkPendingRole.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('000101', '/taskList/checkPendingGroup.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('000101', '/taskList/checkUnreadInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('000101', '/taskList/checkPendingPIGD.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('000101', '/taskList/checkPendingDn.action', FALSE, TRUE);


-- Administration Module
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100001', 'Admin-Common - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100001', '/admin/initCommonFig.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100002', 'Admin-Common - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100002', '/admin/saveCommonFig.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100003', 'Admin-Housekeeping - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100003', '/admin/initHsekeep.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100004', 'Admin-Housekeeping - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100004', '/admin/saveHsekeep.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100005', 'Admin-Password Rule - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100005', '/admin/initPwdRule.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100006', 'Admin-Password Rule - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100006', '/admin/savePwdRule.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100007', 'Admin-Password Dictionary - [Upload]', 0, FALSE, 'OTHER', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100007', '/admin/uploadDict.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100008', 'Admin-Password Dictionary - [Download]', 0, FALSE, 'OTHER', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100008', '/admin/downloadDict.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100009', 'Admin-Reserve Message - [Search]', 0, FALSE, 'SEARCH', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100009', '/admin/initMsg.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100009', '/admin/searchMsg.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100009', '/admin/dataMsg.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100010', 'Admin-Reserve Message - [Create]', 0, FALSE, 'CREATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100010', '/admin/initAddMsg.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100010', '/admin/saveAddMsg.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100011', 'Admin-Reserve Message - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100011', '/admin/viewMsg.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100012', 'Admin-Reserve Message - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100012', '/admin/initEditMsg.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100012', '/admin/saveEditMsg.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100013', 'Admin-Reserve Message - [Delete]', 0, FALSE, 'DELETE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100013', '/admin/saveDeleteMsg.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100014', 'Admin-Summary Page Setting - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100014', '/admin/initMsgSummaryPageSetting.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100014', '/admin/getSummaryFields.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100015', 'Admin-Summary Page Setting - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100015', '/admin/saveMsgSummaryPageSetting.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100016', 'Admin-Retailer Privilege - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100016', '/admin/initEditRetailerPrivilege.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100016', '/admin/getPrivilegeDetail.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100017', 'Admin-Retailer Privilege - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100017', '/admin/savePrivilege.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100018', 'Admin-Email Configuration - [View]', 0, FALSE, 'VIEW', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100018', '/admin/initEmailConfig.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('100019', 'Admin-Email Configuration - [Update]', 0, FALSE, 'UPDATE', '1000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('100019', '/admin/saveEmailConfig.action', FALSE, TRUE);



-- Role Management
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200001', 'Role Profile - [Search]', 0, FALSE, 'SEARCH', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200001', '/role/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200001', '/role/data.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200002', 'Role Profile - [Create]', 0, FALSE, 'CREATE', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200002', '/role/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200002', '/role/saveAdd.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200003', 'Role Profile - [View]', 0, FALSE, 'VIEW', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200003', '/role/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200004', 'Role Profile - [Update]', 0, FALSE, 'UPDATE', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200004', '/role/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200004', '/role/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200005', 'Role Profile - [Delete]', 0, FALSE, 'DELETE', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200005', '/role/saveDelete.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200006', 'Role Profile - [Approve]', 0, FALSE, 'OTHER', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200006', '/role/initApprove.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200006', '/role/saveApprove.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200007', 'Role Profile - [Reject]', 0, FALSE, 'OTHER', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200007', '/role/initReject.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200007', '/role/saveReject.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('200008', 'Role Profile - [Withdraw]', 0, FALSE, 'OTHER', '2000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200008', '/role/initWithdraw.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('200008', '/role/saveWithdraw.action', FALSE, TRUE);



-- User Management
-- User Profile
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300101', 'User Profile - [Search]', 0, FALSE, 'SEARCH', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300101', '/user/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300101', '/user/data.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300102', 'User Profile - [Create]', 0, FALSE, 'CREATE', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300102', '/user/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300102', '/user/saveAdd.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300103', 'User Profile - [View]', 0, FALSE, 'VIEW', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300103', '/user/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300104', 'User Profile - [Update]', 0, FALSE, 'UPDATE', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300104', '/user/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300104', '/user/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300105', 'User Profile - [Delete]', 0, FALSE, 'DELETE', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300105', '/user/saveDelete.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300106', 'User Profile - [Approve]', 0, FALSE, 'OTHER', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300106', '/user/initApprove.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300106', '/user/saveApprove.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300107', 'User Profile - [Reject]', 0, FALSE, 'OTHER', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300107', '/user/initReject.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300107', '/user/saveReject.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300108', 'User Profile - [Withdraw]', 0, FALSE, 'OTHER', '3001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300108', '/user/initWithdraw.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300108', '/user/saveWithdraw.action', FALSE, TRUE);

-- AD User Import
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('300201', 'AD User Import - [import]', 0, FALSE, 'SEARCH', '3002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('300201', '/userImport/import.action', FALSE, TRUE);


-- Group Management
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400001', 'Group Profile - [Search]', 0, FALSE, 'SEARCH', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400001', '/group/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400001', '/group/data.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400002', 'Group Profile - [Create]', 0, FALSE, 'CREATE', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400002', '/group/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400002', '/group/saveAdd.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400003', 'Group Profile - [View]', 0, FALSE, 'VIEW', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400003', '/group/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400004', 'Group Profile - [Update]', 0, FALSE, 'UPDATE', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400004', '/group/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400004', '/group/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400005', 'Group Profile - [Delete]', 0, FALSE, 'DELETE', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400005', '/group/saveDelete.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400006', 'Group Profile - [Approve]', 0, FALSE, 'OTHER', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400006', '/group/initApprove.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400006', '/group/saveApprove.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400007', 'Group Profile - [Reject]', 0, FALSE, 'OTHER', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400007', '/group/initReject.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400007', '/group/saveReject.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('400008', 'Group Profile - [Withdraw]', 0, FALSE, 'OTHER', '4000', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400008', '/group/initWithdraw.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('400008', '/group/saveWithdraw.action', FALSE, TRUE);




-- Buyer Profile
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500101', 'Buyer Profile - [Search]', 0, FALSE, 'SEARCH', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500101', '/buyer/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500101', '/buyer/data.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500102', 'Buyer Profile - [Create]', 0, FALSE, 'CREATE', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500102', '/buyer/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500102', '/buyer/saveAdd.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500103', 'Buyer Profile - [View]', 0, FALSE, 'VIEW', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500103', '/buyer/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500104', 'Buyer Profile - [Update]', 0, FALSE, 'UPDATE', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500104', '/buyer/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500104', '/buyer/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500105', 'Buyer Profile - [Delete]', 0, FALSE, 'DELETE', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500105', '/buyer/saveDelete.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500106', 'Buyer Profile - [Edit Msg Setting]', 0, FALSE, 'UPDATE', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500106', '/buyer/initEditMsgSetting.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500106', '/buyer/saveEditMsgSetting.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500107', 'Buyer Profile - [Edit Business Rule]', 0, FALSE, 'UPDATE', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500107', '/buyer/initEditBusinessRule.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500107', '/buyer/getFuncIdSByGroup.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500107', '/buyer/saveBusinessRule.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500108', 'Buyer Profile - [View Msg Setting]', 0, FALSE, 'UPDATE', '5001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500108', '/buyer/initViewMsgSetting.action', FALSE, TRUE);


-- Buyer Store
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500201', 'Buyer Store - [Search]', 0, FALSE, 'SEARCH', '5002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500201', '/buyerStore/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500201', '/buyerStore/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500202', 'Buyer Store - [View]', 0, FALSE, 'VIEW', '5002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500202', '/buyerStore/viewStore.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500202', '/buyerStore/viewArea.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500203', 'Buyer Store - [Assign]', 0, FALSE, 'OTHER', '5002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500203', '/buyerStore/assignStore.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500203', '/buyerStore/saveAssignStore.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500203', '/buyerStore/assignArea.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500203', '/buyerStore/saveAssignArea.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('500204', 'Buyer Store - [Export Excel]', 0, FALSE, 'OTHER', '5002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('500204', '/buyerStore/exportStoreExcel.action', FALSE, TRUE);



-- Supplier Profile
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600101', 'Supplier Profile - [Search]', 0, FALSE, 'SEARCH', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600101', '/supplier/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600101', '/supplier/data.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600102', 'Supplier Profile - [Create]', 0, FALSE, 'CREATE', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600102', '/supplier/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600102', '/supplier/saveAdd.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600103', 'Supplier Profile - [View]', 0, FALSE, 'VIEW', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600103', '/supplier/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600104', 'Supplier Profile - [Update]', 0, FALSE, 'UPDATE', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600104', '/supplier/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600104', '/supplier/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600105', 'Supplier Profile - [Delete]', 0, FALSE, 'DELETE', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600105', '/supplier/saveDelete.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600106', 'Supplier Profile - [Edit Msg Setting]', 0, FALSE, 'UPDATE', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600106', '/supplier/initEditMsgSetting.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600106', '/supplier/saveEditMsgSetting.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600107', 'Supplier Profile - [Edit Term And Condition]', 0, FALSE, 'UPDATE', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600107', '/supplier/initEditTermAndCondition.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600107', '/supplier/saveEditTermAndCondition.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600107', '/supplier/removeTermAndCondition.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600109', 'Supplier Profile - [View Msg Setting]', 0, FALSE, 'UPDATE', '6001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600109', '/supplier/initViewMsgSetting.action', FALSE, TRUE);





-- TradingPartner Profile
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600201', 'Trading Partner - [Search]', 0, FALSE, 'SEARCH', '6002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600201', '/tp/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600201', '/tp/data.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600202', 'Trading Partner - [Create]', 0, FALSE, 'CREATE', '6002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600202', '/tp/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600202', '/tp/saveAdd.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600203', 'Trading Partner - [View]', 0, FALSE, 'VIEW', '6002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600203', '/tp/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600204', 'Trading Partner - [Update]', 0, FALSE, 'UPDATE', '6002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600204', '/tp/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600204', '/tp/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600205', 'Trading Partner - [Delete]', 0, FALSE, 'DELETE', '6002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600205', '/tp/saveDelete.action', FALSE, TRUE);

-- Supplier Set
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600301', 'Supplier Group - [Search]', 0, FALSE, 'SEARCH', '6003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600301', '/supplierSet/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600301', '/supplierSet/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600302', 'Supplier Group - [Create]', 0, FALSE, 'CREATE', '6003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600302', '/supplierSet/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600302', '/supplierSet/saveAdd.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600303', 'Supplier Group - [View]', 0, FALSE, 'VIEW', '6003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600303', '/supplierSet/view.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600304', 'Supplier Group - [Update]', 0, FALSE, 'UPDATE', '6003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600304', '/supplierSet/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600304', '/supplierSet/saveEdit.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('600305', 'Supplier Group - [Delete]', 0, FALSE, 'DELETE', '6003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('600305', '/supplierSet/delete.action', FALSE, TRUE);


-- Application Support

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('700101', 'Log File - [Search]', 0, FALSE, 'SEARCH', '7001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('700101', '/log/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('700101', '/log/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('700102', 'Log File - [Download]', 0, FALSE, 'OTHER', '7001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('700102', '/log/saveDownload.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('700103', 'Log File - [View]', 0, FALSE, 'VIEW', '7001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('700103', '/log/view.action', FALSE, TRUE);

-- Audit Trail
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('800101', 'Audit Trail - [Search]', 0, FALSE, 'SEARCH', '8001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800101', '/auditTrail/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800101', '/auditTrail/data.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800101', '/auditTrail/searchSession.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800101', '/auditTrail/dataSession.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('800102', 'Audit Trail File - [Download]', 0, FALSE, 'OTHER', '8001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800102', '/auditTrail/saveDownload.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800102', '/auditTrail/checkSession.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('800201', 'System Access - [Search]', 0, FALSE, 'SEARCH', '8002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800201', '/auditAccess/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800201', '/auditAccess/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('800202', 'System Access File - [Download]', 0, FALSE, 'OTHER', '8002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('800202', '/auditAccess/saveDownload.action', FALSE, TRUE);

-- Purchase Order
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900101', 'Purchase Order - [Search]', 0, FALSE, 'SEARCH', '9001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900101', '/po/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900101', '/po/data.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900101', '/po/searchSession.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900101', '/po/dataSession.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900102', 'Purchase Order - [Generate Invoice]', 1, FALSE, 'OTHER', '9001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900102', '/po/generateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900102', '/po/invoiceData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900102', '/po/save.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900102', '/po/saveAndSent.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900102', '/po/saveCn.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900102', '/po/saveAndSentCn.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900103', 'Purchase Order - [View PDF]', 2, FALSE, 'OTHER', '9001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900103', '/po/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900104', 'Purchase Order - [Export Excel]', 3, FALSE, 'OTHER', '9001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900104', '/po/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900105', 'Purchase Order - [Edit Delivery Date]', 4, FALSE, 'OTHER', '9001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900105', '/po/initEditDeliveryDate.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900105', '/po/saveEditDeliveryDate.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900106', 'Purchase Order - [Export Summary Excel]', 5, FALSE, 'OTHER', '9001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900106', '/po/exportSummaryExcel.action', FALSE, TRUE);


-- Return to Vendor
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900201', 'Return to Vendor - [Search]', 0, FALSE, 'SEARCH', '9002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900201', '/rtv/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900201', '/rtv/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900202', 'Return to Vendor - [View PDF]', 0, FALSE, 'OTHER', '9002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900202', '/rtv/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900203', 'Return to Vendor - [Export Excel]', 0, FALSE, 'OTHER', '9002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900203', '/rtv/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900204', 'Return to Vendor - [Export Summary Excel]', 0, FALSE, 'OTHER', '9002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900204', '/rtv/exportSummaryExcel.action', FALSE, TRUE);


-- Goods Receipt Note
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900301', 'Goods Receipt Note - [Search]', 0, FALSE, 'SEARCH', '9003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900301', '/grn/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900301', '/grn/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900302', 'Goods Receipt Note - [View PDF]', 0, FALSE, 'OTHER', '9003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900302', '/grn/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900303', 'Goods Receipt Note - [Audit]', 0, FALSE, 'OTHER', '9003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900303', '/grn/initAudit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900303', '/grn/saveApprove.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900303', '/grn/saveReject.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900304', 'Goods Receipt Note - [Dispute]', 0, FALSE, 'OTHER', '9003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900304', '/grn/initDispute.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900304', '/grn/saveDispute.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900305', 'Goods Receipt Note - [Export Excel]', 0, FALSE, 'OTHER', '9003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900305', '/grn/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900306', 'Goods Receipt Note - [Export Summary Excel]', 0, FALSE, 'OTHER', '9003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900306', '/grn/exportSummaryExcel.action', FALSE, TRUE);



-- E-Invoice
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900401', 'E-Invoice - [Search]', 0, FALSE, 'SEARCH', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900401', '/inv/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900401', '/inv/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900402', 'E-Invoice - [View PDF]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900402', '/inv/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900403', 'E-Invoice - [Sent]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900403', '/inv/sent.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900404', 'E-Invoice - [Edit]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900404', '/inv/initEdit.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900405', 'E-Invoice - [Generate New For Void]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900405', '/inv/initGenerateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900405', '/inv/saveGenerateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900405', '/inv/saveAndSentGenerateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900405', '/inv/checkMatchingRecordExist.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900406', 'E-Invoice - [Void E-Invoice]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900406', '/inv/voidInvoice.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900407', 'E-Invoice - [Export Excel]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900407', '/inv/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900408', 'E-Invoice - [Export Summary Excel]', 0, FALSE, 'OTHER', '9004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900408', '/inv/exportSummaryExcel.action', FALSE, TRUE);



-- Debit Note
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900501', 'Debit Note - [Search]', 0, FALSE, 'SEARCH', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900501', '/dn/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900501', '/dn/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900502', 'Debit Note - [View PDF]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900502', '/dn/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900503', 'Debit Note - [Approve]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900503', '/dn/approve.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900503', '/dn/reject.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900503', '/dn/checkSentStatus.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900504', 'Debit Note - [Edit]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900504', '/dn/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900504', '/dn/saveEdit.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900505', 'Debit Note - [Create]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900505', '/dn/initAdd.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900505', '/dn/saveAdd.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900506', 'Debit Note - [Delete]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900506', '/dn/saveDelete.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900507', 'Debit Note - [Dispute]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900507', '/dn/initDispute.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900507', '/dn/saveDispute.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900508', 'Debit Note - [Price Approval]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900508', '/dn/initAuditPrice.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900508', '/dn/saveAuditPrice.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900509', 'Debit Note - [Qty Approval]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900509', '/dn/initAuditQty.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900509', '/dn/saveAuditQty.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900510', 'Debit Note - [Close]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900510', '/dn/initClose.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900510', '/dn/saveClose.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900511', 'Debit Note - [Export Excel]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900511', '/dn/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900512', 'Debit Note - [Export Summary Excel]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900512', '/dn/exportSummaryExcel.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900513', 'Debit Note - [CloseWithoutEdit]', 0, FALSE, 'OTHER', '9005', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900513', '/dn/initCloseWithoutEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900513', '/dn/saveClose.action', FALSE, TRUE);


-- Delivery Order
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900601', 'Delivery Order - [Search]', 0, FALSE, 'SEARCH', '9006', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900601', '/do/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900601', '/do/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900602', 'Delivery Order - [View PDF]', 0, FALSE, 'OTHER', '9006', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900602', '/do/print.action', FALSE, TRUE);

-- Payment Advice
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900701', 'Payment Advice - [Search]', 0, FALSE, 'SEARCH', '9007', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900701', '/pn/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900701', '/pn/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900702', 'Payment Advice - [View PDF]', 0, FALSE, 'OTHER', '9007', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900702', '/pn/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900703', 'Payment Advice - [Export Excel]', 0, FALSE, 'OTHER', '9007', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900703', '/pn/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900704', 'Payment Advice - [Export Summary Excel]', 0, FALSE, 'OTHER', '9007', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900704', '/pn/exportSummaryExcel.action', FALSE, TRUE);


-- Item In
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900801', 'ItemIn Master - [Search]', 0, FALSE, 'SEARCH', '9008', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900801', '/itemIn/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900801', '/itemIn/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900802', 'ItemIn Master - [Upload]', 0, FALSE, 'SEARCH', '9008', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900802', '/itemIn/initUpload.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900802', '/itemIn/save.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900802', '/itemIn/saveAndSend.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900803', 'ItemIn Master - [Send]', 0, FALSE, 'DELETE', '9008', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900803', '/itemIn/send.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900804', 'ItemIn Master - [Delete]', 0, FALSE, 'DELETE', '9008', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900804', '/itemIn/delete.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900805', 'ItemIn Master - [Download Original File]', 0, FALSE, 'DELETE', '9008', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900805', '/itemIn/downloadOriginalFile.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900806', 'ItemIn Master - [Download Exchange File]', 0, FALSE, 'DELETE', '9008', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900806', '/itemIn/downloadExchangeFile.action', FALSE, TRUE);

-- Item Out
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900901', 'ItemOut Master - [Search]', 0, FALSE, 'SEARCH', '9009', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900901', '/itemOut/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900901', '/itemOut/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900902', 'ItemOut Master - [Download Original File]', 0, FALSE, 'DELETE', '9009', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900902', '/itemOut/downloadOriginalFile.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('900903', 'ItemOut Master - [Download Exchange File]', 0, FALSE, 'DELETE', '9009', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('900903', '/itemOut/downloadExchangeFile.action', FALSE, TRUE);


-- Goods Issued
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901001', 'Goods Issued - [Search]', 0, FALSE, 'SEARCH', '9010', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901001', '/gi/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901001', '/gi/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901002', 'Goods Issued - [View PDF]', 0, FALSE, 'OTHER', '9010', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901002', '/gi/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901003', 'Goods Issued - [Export Excel]', 0, FALSE, 'OTHER', '9010', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901003', '/gi/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901004', 'Goods Issued - [Export Summary Excel]', 0, FALSE, 'OTHER', '9010', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901004', '/gi/exportSummaryExcel.action', FALSE, TRUE);


-- Credit Claim
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901101', 'Credit Claim - [Search]', 0, FALSE, 'SEARCH', '9011', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901101', '/cc/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901101', '/cc/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901102', 'Credit Claim - [View PDF]', 0, FALSE, 'OTHER', '9011', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901102', '/cc/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901103', 'Credit Claim - [Export Excel]', 0, FALSE, 'OTHER', '9011', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901103', '/cc/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901104', 'Credit Claim - [Export Summary Excel]', 0, FALSE, 'OTHER', '9011', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901104', '/cc/exportSummaryExcel.action', FALSE, TRUE);


-- Matching Report
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000101', 'PO-INV-GRN-DN Matching - [Search]', 0, FALSE, 'SEARCH', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000101', '/poInvGrnDnMatching/init.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000101', '/poInvGrnDnMatching/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000101', '/poInvGrnDnMatching/data.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000102', 'PO-INV-GRN-DN Matching - [Export Excel]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000102', '/poInvGrnDnMatching/exportExcel.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000103', 'PO-INV-GRN-DN Matching - [Approve]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000103', '/poInvGrnDnMatching/saveApprove.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000104', 'PO-INV-GRN-DN Matching - [Accept and Reject]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000104', '/poInvGrnDnMatching/saveAcceptOrReject.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000105', 'PO-INV-GRN-DN Matching - [QTY Approval]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000105', '/poInvGrnDnMatching/initAuditQty.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000105', '/poInvGrnDnMatching/saveAudit.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000106', 'PO-INV-GRN-DN Matching - [Price Approval]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000106', '/poInvGrnDnMatching/initAuditPrice.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000106', '/poInvGrnDnMatching/saveAudit.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000107', 'PO-INV-GRN-DN Matching - [Close]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000107', '/poInvGrnDnMatching/initClose.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000107', '/poInvGrnDnMatching/saveClose.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000108', 'PO-INV-GRN-DN Matching - [View Details]', 0, FALSE, 'OTHER', '10001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000108', '/poInvGrnDnMatching/viewDetails.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000108', '/poInvGrnDnMatching/checkAcceptOrReject.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000201', 'Matching Run Summary Report - [Export Excel]', 0, FALSE, 'OTHER', '10002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000201', '/summaryReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000201', '/summaryReport/checkExcelData.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1000301', 'Matching Discrepancy Report - [Export Excel]', 0, FALSE, 'OTHER', '10003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000301', '/discrepancyReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1000301', '/discrepancyReport/checkExcelData.action', FALSE, TRUE);


-- Report
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100101', 'Read Status Report - [Export Excel]', 0, FALSE, 'OTHER', '11001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100101', '/readStatusReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100101', '/readStatusReport/checkExcelData.action', FALSE, TRUE);



insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100201', 'Tracking Report - [DN Resolution Report]', 0, FALSE, 'OTHER', '11002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100201', '/trackingReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100201', '/trackingReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100201', '/trackingReport/dnResolution.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100202', 'Tracking Report - [DN Outstanding Report]', 0, FALSE, 'OTHER', '11002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100202', '/trackingReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100202', '/trackingReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100202', '/trackingReport/dnOutstanding.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100203', 'Tracking Report - [Matching Resolution Report]', 0, FALSE, 'OTHER', '11002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100203', '/trackingReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100203', '/trackingReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100203', '/trackingReport/matchingResolution.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100204', 'Tracking Report - [Matching Outstanding Report]', 0, FALSE, 'OTHER', '11002', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100204', '/trackingReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100204', '/trackingReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100204', '/trackingReport/matchingOutstanding.action', FALSE, TRUE);



insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100301', 'Data Export Report - [E-Invoice Export Report]', 0, FALSE, 'OTHER', '11003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100301', '/dataExportReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100301', '/dataExportReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100301', '/dataExportReport/invExport.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100302', 'Data Export Report - [DN Export Report]', 0, FALSE, 'OTHER', '11003', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100302', '/dataExportReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100302', '/dataExportReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100302', '/dataExportReport/dnExport.action', FALSE, TRUE);


insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100401', 'Missing Docs Report - [GRN Report]', 0, FALSE, 'OTHER', '11004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100401', '/missingDocsReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100401', '/missingDocsReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100401', '/missingDocsReport/missGrn.action', FALSE, TRUE);
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100402', 'Missing Docs Report - [GI Report]', 0, FALSE, 'OTHER', '11004', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100402', '/missingDocsReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100402', '/missingDocsReport/checkExcelData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100402', '/missingDocsReport/missGi.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('1100601', 'Dn Discrepancy Report - [Export Excel]', 0, FALSE, 'OTHER', '11006', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100601', '/dnDiscrepancyReport/printExcel.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('1100601', '/dnDiscrepancyReport/checkExcelData.action', FALSE, TRUE);

-- Job
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('2000101', 'Job Control - [Setting]', 0, FALSE, 'UPDATE', '20001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2000101', '/jobControl/initEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2000101', '/jobControl/saveEdit.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2000101', '/jobControl/init.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2000101', '/jobControl/saveEditEnabled.action', FALSE, TRUE);


-- Quick Purchase Order
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901201', 'Quick Purchase Order - [Search]', 0, FALSE, 'SEARCH', '9012', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901201', '/quickPo/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901201', '/quickPo/data.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901201', '/quickPo/searchSession.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901201', '/quickPo/dataSession.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901202', 'Quick Purchase Order - [Generate Invoice]', 1, FALSE, 'OTHER', '9012', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/generateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/invoiceData.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/save.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/saveAndSent.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/initBatchGenerateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/saveBatchGenerateInv.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901202', '/quickPo/saveAndSentBatchGenerateInv.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901203', 'Quick Purchase Order - [View PDF]', 2, FALSE, 'OTHER', '9012', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901203', '/quickPo/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901204', 'Quick Purchase Order - [Export Excel]', 3, FALSE, 'OTHER', '9012', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901204', '/quickPo/exportExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901206', 'Quick Purchase Order - [Export Summary Excel]', 5, FALSE, 'OTHER', '9012', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901206', '/quickPo/exportSummaryExcel.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901207', 'Quick Purchase Order - [Edit Invoice No]', 6, FALSE, 'OTHER', '9012', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901207', '/quickPo/initEditInvoiceNo.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901207', '/quickPo/saveEditInvoiceNo.action', FALSE, TRUE);


-- Sales Data
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901301', 'Daily Sales Data - [Search]', 0, FALSE, 'SEARCH', '9013', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901301', '/sales/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901301', '/sales/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901302', 'Daily Sales Data - [View PDF]', 0, FALSE, 'SEARCH', '9013', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901302', '/sales/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901303', 'Daily Sales Data - [Export Excel]', 3, FALSE, 'OTHER', '9013', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901303', '/sales/exportExcel.action', FALSE, TRUE);



-- Credit Note
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901401', 'Credit Note - [Search]', 0, FALSE, 'SEARCH', '9014', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901401', '/cn/search.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901401', '/cn/data.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901402', 'Credit Note - [View PDF]', 0, FALSE, 'OTHER', '9014', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901402', '/cn/print.action', FALSE, TRUE);

insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('901403', 'Credit Note - [send]', 0, FALSE, 'OTHER', '9014', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('901403', '/cn/send.action', FALSE, TRUE);



-- Test Docs
insert into OPERATION(OPN_ID, OPN_DESC, OPN_ORDER, IMPLICIT, OPT_TYPE, MODULE_ID, BUTTON_TITLE_KEY, NEED_AUTH)
VALUES('2100101', 'Generate Batch Invoice - [Other]', 0, FALSE, 'SEARCH', '21001', '', TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2100101', '/testDocs/initGenerateBatchInvoice.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2100101', '/testDocs/checkGenerateBatchInvoice.action', FALSE, TRUE);
insert into OPERATION_URL(OPN_ID, ACCESS_URL, IMPLICIT, NEED_AUTH)
VALUES('2100101', '/testDocs/saveGenerateBatchInvoice.action', FALSE, TRUE);

