DELIMITER $$

DROP PROCEDURE IF EXISTS `SP_OID_GENERIC`$$
CREATE PROCEDURE  `SP_OID_GENERIC`()
BEGIN
    START TRANSACTION;
    update OID_GENERIC set OID = OID+1;
    select OID from OID_GENERIC;
    commit;
END $$

DELIMITER ;