insert into USER_PROFILE(USER_OID, USER_NAME, SALUTATION, LOGIN_ID, LOGIN_PWD, LOGIN_MODE, GENDER, TEL, MOBILE, FAX, EMAIL, FAIL_ATTEMPTS, LAST_RESET_PWD_DATE, LAST_LOGIN_DATE, ACTIVE, BLOCKED, BLOCK_REMARKS, INIT, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, BLOCK_DATE, BLOCK_BY, INACTIVATE_DATE, INACTIVATE_BY, USER_TYPE, BUYER_OID, SUPPLIER_OID)
VALUES(1, 'Admin 1', 'Mr.', 'admin1', '8d193d7def59b438c7347d80a3c9c9b2b97ae635c4d928cae5acadcf8ae3c0ecf531bf3c8e18557a37ad29516b410ef70829dd7c85740d81397b3fddb6df5b1e', 'PASSWORD', 'M', '02584625046', '18652022500', NULL, 'louyang2@pracbiz.com', 0, NULL, NULL, TRUE, FALSE, NULL, TRUE, now(), 'SYSTEM', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL);
insert into T_USER_PROFILE(USER_OID, USER_NAME, SALUTATION, LOGIN_ID, LOGIN_PWD, LOGIN_MODE, GENDER, TEL, MOBILE, FAX, EMAIL, FAIL_ATTEMPTS, LAST_RESET_PWD_DATE, LAST_LOGIN_DATE, ACTIVE, BLOCKED, BLOCK_REMARKS, INIT, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, BLOCK_DATE, BLOCK_BY, INACTIVATE_DATE, INACTIVATE_BY, USER_TYPE, BUYER_OID, SUPPLIER_OID, ACTOR, ACTION_TYPE, ACTION_DATE, CTRL_STATUS)
VALUES(1, 'Admin 1', 'Mr.', 'admin1', '8d193d7def59b438c7347d80a3c9c9b2b97ae635c4d928cae5acadcf8ae3c0ecf531bf3c8e18557a37ad29516b410ef70829dd7c85740d81397b3fddb6df5b1e', 'PASSWORD', 'M', '02584625046', '18652022500', NULL, 'louyang2@pracbiz.com', 0, NULL, NULL, TRUE, FALSE, NULL, TRUE, now(), 'SYSTEM', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'SYSTEM', 'CREATE', now(), 'APPROVED');

insert into USER_PROFILE(USER_OID, USER_NAME, SALUTATION, LOGIN_ID, LOGIN_PWD, LOGIN_MODE, GENDER, TEL, MOBILE, FAX, EMAIL, FAIL_ATTEMPTS, LAST_RESET_PWD_DATE, LAST_LOGIN_DATE, ACTIVE, BLOCKED, BLOCK_REMARKS, INIT, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, BLOCK_DATE, BLOCK_BY, INACTIVATE_DATE, INACTIVATE_BY, USER_TYPE, BUYER_OID, SUPPLIER_OID)
VALUES(2, 'Admin 2', 'Mr.', 'admin2', 'd0c1fe7887579f83a84f2fb8a6ab5eb382bfaa0c89e6dea03f432f6e135b7f92d09d8342d0bd038cf48dae8ee05c405c0c81d57a18b49b2fd4c03ace56a3afa8', 'PASSWORD', 'M', '02584625046', '18652022500', NULL, 'louyang2@pracbiz.com', 0, NULL, NULL, TRUE, FALSE, NULL, TRUE, now(), 'SYSTEM', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL);
insert into T_USER_PROFILE(USER_OID, USER_NAME, SALUTATION, LOGIN_ID, LOGIN_PWD, LOGIN_MODE, GENDER, TEL, MOBILE, FAX, EMAIL, FAIL_ATTEMPTS, LAST_RESET_PWD_DATE, LAST_LOGIN_DATE, ACTIVE, BLOCKED, BLOCK_REMARKS, INIT, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, BLOCK_DATE, BLOCK_BY, INACTIVATE_DATE, INACTIVATE_BY, USER_TYPE, BUYER_OID, SUPPLIER_OID, ACTOR, ACTION_TYPE, ACTION_DATE, CTRL_STATUS)
VALUES(2, 'Admin 2', 'Mr.', 'admin2', 'd0c1fe7887579f83a84f2fb8a6ab5eb382bfaa0c89e6dea03f432f6e135b7f92d09d8342d0bd038cf48dae8ee05c405c0c81d57a18b49b2fd4c03ace56a3afa8', 'PASSWORD', 'M', '02584625046', '18652022500', NULL, 'louyang2@pracbiz.com', 0, NULL, NULL, TRUE, FALSE, NULL, TRUE, now(), 'SYSTEM', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'SYSTEM', 'CREATE', now(), 'APPROVED');



insert into ROLE(ROLE_OID, ROLE_ID, ROLE_NAME, ROLE_TYPE, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, CREATED_FROM_SYSADMIN, USER_TYPE_OID, BUYER_OID)
VALUES(1, 'root', 'root', 'ADMIN', now(), 'SYSTEM', NULL, NULL, TRUE, 1, NULL);
insert into T_ROLE(ROLE_OID, ROLE_ID, ROLE_NAME, ROLE_TYPE, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, CREATED_FROM_SYSADMIN, USER_TYPE_OID, BUYER_OID, ACTOR, ACTION_TYPE, ACTION_DATE, CTRL_STATUS)
VALUES(1, 'root', 'root', 'ADMIN', now(), 'SYSTEM', NULL, NULL, TRUE, 1, NULL, 'SYSTEM', 'CREATE', now(), 'APPROVED');

-- insert into ROLE(ROLE_OID, ROLE_ID, ROLE_NAME, ROLE_TYPE, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, CREATED_FROM_SYSADMIN, USER_TYPE_OID, BUYER_OID)
-- VALUES(2, 'Admin_Checker', 'Administrator Checker', 'ADMIN', now(), 'SYSTEM', NULL, NULL, TRUE, 1, NULL);
-- insert into T_ROLE(ROLE_OID, ROLE_ID, ROLE_NAME, ROLE_TYPE, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, CREATED_FROM_SYSADMIN, USER_TYPE_OID, BUYER_OID, ACTOR, ACTION_TYPE, ACTION_DATE, CTRL_STATUS)
-- VALUES(2, 'Admin_Checker', 'Administrator Checker', 'ADMIN', now(), 'SYSTEM', NULL, NULL, TRUE, 1, NULL, 'SYSTEM', 'CREATE', now(), 'APPROVED');


insert into ROLE_USER(ROLE_OID, USER_OID) VALUES(1, 1);
insert into T_ROLE_USER(ROLE_OID, USER_OID) VALUES(1, 1);

insert into ROLE_USER(ROLE_OID, USER_OID) VALUES(1, 2);
insert into T_ROLE_USER(ROLE_OID, USER_OID) VALUES(1, 2);


-- Role root
-- Task List
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '000101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '000101');

-- Administrator
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100001');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100002');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100003');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100004');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100005');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100006');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100007');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100008');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100009');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100010');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100011');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100012');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100013');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100014');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100015');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100016');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100017');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100018');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100019');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100001');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100002');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100003');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100004');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100005');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100006');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100007');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100008');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100009');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100010');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100011');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100012');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100013');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100014');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100015');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100016');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100017');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100018');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '100019');

-- Role Management
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200001');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200002');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200003');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200004');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200005');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200006');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200007');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200008');

insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200001');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200002');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200003');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200004');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200005');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200006');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200007');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '200008');

-- User Management
-- User Profile
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300101');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300102');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300103');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300104');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300105');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300106');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300107');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300108');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300102');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300103');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300104');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300105');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300106');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300107');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '300108');

-- Group Management
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400001');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400002');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400003');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400004');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400005');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400006');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400007');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400008');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400001');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400002');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400003');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400004');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400005');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400006');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400007');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '400008');

-- Buyer Profile
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500101');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500102');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500103');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500104');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500105');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500106');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500107');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500108');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500102');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500103');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500104');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500105');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500106');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500107');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '500108');

-- Supplier Profile
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600101');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600102');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600103');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600104');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600105');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600106');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600107');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600109');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600102');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600103');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600104');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600105');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600106');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600107');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600109');

-- Trading Partner
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600201');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600202');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600203');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600204');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600205');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600201');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600202');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600203');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600204');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600205');


-- Supplier Set
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600301');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600302');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600303');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600304');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600305');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600301');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600302');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600303');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600304');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '600305');

-- Application Support
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '700101');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '700102');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '700103');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '700101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '700102');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '700103');

-- Audit Trail
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800101');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800102');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800201');
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800202');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800102');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800201');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '800202');

-- Job Control
insert into ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '2000101');
insert into T_ROLE_OPERATION(ROLE_OID, OPN_ID) VALUES(1, '2000101');